kafka:
  in.topic: icc-detail-in-topic
  out.topic: icc-detail-out-topic
  group: iacc
  bootstrap.servers: localhost:9092

#путь до json схемы для валидации входях сообщений, может быть пустой строкой / либо файл может отсутствовать - в этом случае входящие сообщения не валидируются
in.json.schema.path: data/eksCommissionRequest_schema.json

#путь до директории с примерами исходящих сообщений json. Следует указывать только как путь. Файлы в директории должны соответствовать шаблону *.json
out.json.examples.dir.path: data/out/

#используется для того, чтобы у входящего запроса скопировать поля в исходящий ответ. Ключ - имя поля входящего запроса, значение - имя поля исходящего сообщения.
id.field.mapping: {"from":"payerAccount", "to":"rquid"}